[platformio]
src_dir = esp32/esp_mfr

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = /dev/cu.usbserial-0001
monitor_speed = 115200
lib_deps =
  miguelbalboa/MFRC522@^1.4.11
  adafruit/Adafruit SSD1306@^2.5.13
  adafruit/Adafruit GFX Library@^1.12.1
  olkal/HX711_ADC@^1.2.12
